INSERT INTO Entities (id) values (1)
INSERT INTO Items (entity_id,assetpath,name,type) values (1, 'items/Sword01.PNG', 'sword', 'WEAPON')
INSERT INTO Stats (name,start_range,end_range,entity_id) values ('health', 0, 0, 1)
INSERT INTO Stats (name,start_range,end_range,entity_id) values ('armor', 0, 0, 1)
INSERT INTO Stats (name,start_range,end_range,entity_id) values ('speed', 0, 0, 1)
INSERT INTO Stats (name,start_range,end_range,entity_id) values ('dmg', 30, 50, 1)

INSERT INTO Entities (id) values (2)
INSERT INTO Enemies (entity_id,assetpath,name) values (2, 'players/demon.gif', 'demon')
INSERT INTO Stats (name,start_range,end_range,entity_id) values ('health', 100, 100, 2)
INSERT INTO Stats (name,start_range,end_range,entity_id) values ('armor', 0, 0, 2)
INSERT INTO Stats (name,start_range,end_range,entity_id) values ('speed', 0, 0, 2)
INSERT INTO Stats (name,start_range,end_range,entity_id) values ('dmg', 0, 0, 2)